=== DjobaDELATV/seygo_data/schema/v1/set.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/set.json",
  "title": "Set",
  "description": "A set of Yu-Gi-Oh cards. Sets may be physical (booster pack, structure deck, promo card list, etc) or virtual (Master Duel pack, etc).",
  "type": "object",
  "required": [
    "$schema",
    "id",
    "name",
    "contents",
    "externalIDs"
  ],
  "properties": {
    "$schema": {
      "const": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/set.json"
    },
    "id": {
      "description": "The UUID of this set. The name of the set's file should be this UUID.",
      "type": "string",
      "format": "uuid"
    },
    "date": {
      "description": "The release date for this product, if known. Only used in virtual sets.",
      "type": "string",
      "format": "date"
    },
    "name": {
      "description": "A mapping of language to set names. In physical sets, if the locales object has a mapping for this language, then this name is official, else it is unofficial.",
      "type": "object",
      "propertyNames": {
        "$ref": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/language.json"
      },
      "additionalProperties": {
        "type": "string"
      }
    },
    "locales": {
      "description": "A mapping of locale to locale-specific information. Only used in physical sets.",
      "type": "object",
      "propertyNames": {
        "$ref": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/locale.json"
      },
      "remainingProperties": {
        "description": "Locale-specific information for this set.",
        "type": "object",
        "required": [
          "language",
          "cardImages",
          "externalIDs"
        ],
        "properties": {
          "language": {
            "description": "The default language for this product. Individual cards may have different languages.",
            "type": "string"
          },
          "prefix": {
            "description": "The card code prefix for this locale. This should be everything before the number part of the card code. This includes the dash, if no language code is present! If null, indicates that this locale did not use card codes at all, a la old OCG sets.",
            "type": "string"
          },
          "date": {
            "description": "The release date for this product, if known.",
            "type": "string",
            "format": "date"
          },
          "image": {
            "description": "A URL to a image of this set in this locale, if available. Use this in preference to the 'image' field in 'contents'.",
            "type": "string",
            "format": "uri"
          },
          "boxImage": {
            "description": "A URL to a image of this set's booster box in this locale, if available. Use this in preference to the 'image' field in 'contents'. Deprecated; find the sealed product with the boxOf property set to this instead.",
            "type": "string",
            "format": "uri",
            "deprecated": true
          },
          "cardImages": {
            "description": "A mapping of editions (as per the edition enumeration, or the empty string if no edition) to sets of card images in this locale. Deprecated, use 'cardInfo' instead.",
            "type": "object",
            "additionalProperties": {
              "description": "A mapping of printing UUIDs to images of that card's specific printing in this locale.",
              "type": "object",
              "additionalProperties": {
                "description": "A URL to a full image of this card.",
                "type": "string",
                "format": "uri"
              }
            },
            "deprecated": true
          },
          "cardInfo": {
            "description": "A mapping of editions (as per the edition enumeration, or the empty string if no edition) to per-card information in this locale.",
            "type": "object",
            "additionalProperties": {
              "description": "A mapping of printing UUIDs to per-card info in this locale.",
              "type": "object",
              "additionalProperties": {
                "type": "object",
                "description": "Per-card information for this specific locale.",
                "additionalProperties": {
                  "image": {
                    "type": "string",
                    "description": "The URL to the full card image for this printing.",
                    "format": "uri"
                  },
                  "price": {
                    "type": "number",
                    "description": "Price information for this printing, if available. All prices are the most recent available as of the creation of this database, and are normalized to USD. No guarantees are made that this price is accurate, or that all sources were considered, or that the correct locale was considered."
                  }
                }
              }
            }
          },
          "editions": {
            "description": "A list of editions this set was printed in in this locale.",
            "type": "array",
            "items": {
              "description": "An edition. Duel Terminal editions are limited editions.",
              "enum": [
                "1st",
                "unlimited",
                "limited"
              ]
            }
          },
          "formats": {
            "description": "A list of formats this set was printed in in this locale.",
            "type": "array",
            "items": {
              "$ref": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/format.json"
            }
          },
          "externalIDs": {
            "description": "IDs and other information, to access this set from various other sites.",
            "type": "object",
            "required": [],
            "properties": {
              "dbIDs": {
                "description": "Any official Yugioh database IDs for this product.",
                "type": "array",
                "items": {
                  "type": "integer",
                  "description": "An official Yugioh database ID for this product."
                }
              }
            }
          }
        }
      }
    },
    "contents": {
      "description": "The contents of this set. These contents might differ by locale. Virtual sets have just one entry here.",
      "type": "array",
      "items": {
        "description": "Information about a set's contents.",
        "type": "object",
        "required": [
          "formats",
          "cards"
        ],
        "properties": {
          "locales": {
            "description": "The locales these contents apply to. Not present in virtual packs.",
            "type": "array",
            "items": {
              "$ref": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/locale.json"
            }
          },
          "formats": {
            "description": "The widest set of formats in which this these contents were printed into. Prefer the locale format list over this.",
            "deprectated": true,
            "type": "array",
            "items": {
              "enum": [
                "ocg",
                "tcg",
                "speed",
                "masterduel",
                "duellinks"
              ]
            }
          },
          "distrobution": {
            "description": "Either a keyword, or the UUID of the distrobution method of this set, if known: was it a pack, deck, promo card, etc. Look it up in the distributions JSON. As for keywords: The keyword 'preconstructed' means to give all cards in order, like a deck.",
            "anyOf": [
              {
                "type": "string",
                "format": "uuid"
              },
              {
                "enum": [
                  "preconstructed"
                ]
              }
            ]
          },
          "packsPerBox": {
            "description": "How many packs are included per booster box. Used only if this is a pack that can come in boxes. Deprecated; find the sealed product with the boxOf property set to this instead.",
            "type": "integer",
            "deprecated": true
          },
          "hasHobbyRetailDifferences": {
            "description": "Set this to true if this pack has hobby and retail booster boxes, and thier contents may differ with regard to thier secret/ultimate rares. Deprecated; find the sealed product with the boxOf property set to this instead.",
            "type": "boolean",
            "deprecated": true
          },
          "editions": {
            "description": "The widest set of editions these contents were printed into. At least one is required in physical TCG (and some OCG) sets. This is not present in virtual sets. Prefer the locale edition list over this.",
            "deprectated": true,
            "type": "array",
            "items": {
              "enum": [
                "1st",
                "unlimited",
                "limited"
              ]
            }
          },
          "image": {
            "description": "A URL to a image of this set, if available. Use the 'image' field in 'locales' first if also available.",
            "type": "string",
            "format": "uri"
          },
          "boxImage": {
            "description": "A URL to a image of this set's booster box, if available. Use the 'image' field in 'locales' first if also available. Deprecated; find the sealed product with the boxOf property set to this instead.",
            "type": "string",
            "format": "uri",
            "deprecated": true
          },
          "cards": {
            "description": "Cards in this set.",
            "type": "array",
            "items": {
              "$ref": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/printing.json"
            }
          },
          "removedCards": {
            "description": "Cards that were in this set, but have been removed. Used only in virtual sets.",
            "type": "array",
            "items": {
              "$ref": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/printing.json"
            }
          },
          "externalIDs": {
            "description": "IDs and other information, to access this card from various other sites.",
            "type": "object",
            "required": [],
            "properties": {
              "ygoprodeck": {
                "description": "The slug for YGOPRODECK you can use after 'ygoprodeck.com/pack/' to get the set's page.",
                "type": "string"
              }
            }
          },
          "history": {
            "description": "Physical sets have a release date. Virtual sets, furthermore, may also be revoked, and even re-added, at Konami's whim. This array of periods of availability tracks both.",
            "type": "array",
            "items": {
              "description": "A span of time this set was (or is, or will be) available.",
              "type": "object",
              "required": [],
              "properties": {
                "startDate": {
                  "description": "The date this set was made available. Optional, if you don't know when it debuted.",
                  "type": "string",
                  "format": "date"
                },
                "endDate": {
                  "description": "The date this set was revoked. Optional, if it is still available.",
                  "type": "string",
                  "format": "date"
                }
              }
            }
          }
        }
      }
    },
    "externalIDs": {
      "description": "IDs and other information, to access this set from various other sites.",
      "type": "object",
      "required": [],
      "properties": {
        "yugipedia": {
          "description": "Yugipedia information about this set.",
          "type": "object",
          "required": [
            "id",
            "name"
          ],
          "properties": {
            "id": {
              "description": "The internal wiki ID for the Yugipedia page for this set.",
              "type": "integer"
            },
            "name": {
              "description": "The Yugipedia page name for this set.",
              "type": "string"
            }
          }
        },
        "yugiohpricesName": {
          "description": "The name of this set on YugiohPrices. TCG only. Deprecated; YugiohPrices no longer exists.",
          "type": "string",
          "deprecated": true
        }
      }
    }
  }
}

=== DjobaDELATV/seygo_data/sets/32a33531-dcb5-4669-a32c-4785d377f5db.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/set.json",
  "id": "32a33531-dcb5-4669-a32c-4785d377f5db",
  "date": "2025-07-07",
  "name": {
    "en": "Deck Build Box: Buster Assault"
  },
  "contents": [
    {
      "formats": [
        "duellinks"
      ],
      "image": "https://ms.yugipedia.com//2/21/DeckBuildBoxBusterAssault.png",
      "cards": [
        {
          "id": "243dfa85-26b7-4c4a-a7e9-b6154a58a9ff",
          "card": "da30cc79-106a-43e6-9412-2a405869b8f3"
        },
        {
          "id": "a8044b6c-ce3c-4ce7-800b-87149cc4f337",
          "card": "90293308-7da6-4ed2-afa5-a5236a33b12f"
        },
        {
          "id": "78406d1a-f0a9-451a-a27b-26b53762687c",
          "card": "4a50e7a8-1f9e-4c99-85f9-8d5cc4e00401"
        },
        {
          "id": "9e0dd1a5-d9c2-4739-a04a-36213c49dea0",
          "card": "8ea75a70-ac3b-4c9a-8808-67501613da58"
        },
        {
          "id": "dc924144-7c4e-4ccb-90f4-dddf83d82056",
          "card": "0a77d78a-ea91-4362-a92d-daa03cc9d137"
        },
        {
          "id": "dca803cb-9086-4934-924d-e8b93344b17a",
          "card": "4afbab66-9d0f-46c5-9f67-cefb6280c06c"
        },
        {
          "id": "3af335aa-40d4-48dd-9ad5-dbb99078c444",
          "card": "3b528d5f-89a6-43e3-b5d2-8d9c74ee548b"
        },
        {
          "id": "d5ef7d44-e62c-460a-8865-e20cf6d88c29",
          "card": "b981bd29-e837-43b0-aae0-2d029e346949"
        },
        {
          "id": "1ef01a8e-5998-47fe-bd6b-d81f5eb72363",
          "card": "effa37ff-f099-4496-908f-8225cad719cb"
        },
        {
          "id": "10eb1d0d-9c55-4a56-8254-7828a3161158",
          "card": "afd6d9be-9b8e-4c31-90a9-e71674a97492"
        },
        {
          "id": "e453558b-d661-4abe-8248-4561f441ad5b",
          "card": "626245d3-eb77-41f6-b91c-fbf8f990df89"
        },
        {
          "id": "3f71832d-b8b0-4a9c-ac44-8b1a90022a42",
          "card": "e2adc868-1923-44be-992a-a50f828b8890"
        },
        {
          "id": "2de5f055-250f-4304-8bb3-b032963d2942",
          "card": "6e0d3c52-ea36-4712-b248-1861f229ac6d"
        },
        {
          "id": "42fe61ef-1e9e-4265-962a-61fbc2782c0c",
          "card": "212320d0-e09f-46c4-89bf-62c0dd04a30f"
        },
        {
          "id": "a33176a4-2258-4fc1-94e2-ed92e68cfaaa",
          "card": "69b38dae-d222-4dee-a4a9-82af0787663d"
        },
        {
          "id": "2582ba54-8387-48ca-a2f4-95b7a0174476",
          "card": "0fe43d09-758c-49dd-a25c-662355974e54"
        },
        {
          "id": "aaa86054-e363-49be-9bd4-d760bd28fbaa",
          "card": "a21a1fe2-d992-4013-bcf8-19968c3409da"
        },
        {
          "id": "4849b086-b839-4275-9d96-7e4c977a5847",
          "card": "a01e419c-adcb-47e9-800a-398867794eed"
        },
        {
          "id": "56a93bdc-90e4-4092-b6f9-e694a7afc343",
          "card": "ab6fdab4-ae5e-4b8d-b844-1b1a5da8dcaf"
        },
        {
          "id": "50f7598e-fdec-4a19-957f-05f301d97119",
          "card": "03c24ede-afb7-429a-b25b-7833f29bf946"
        },
        {
          "id": "0aad2ff4-7f9a-49e2-84a0-6c9967d182b2",
          "card": "2727e96b-311f-43d6-9326-9dd4f44b9796"
        },
        {
          "id": "ce6067a9-7a32-4591-a726-ebe282c8aabd",
          "card": "55977ecd-30b7-445c-84f6-ace253572288"
        },
        {
          "id": "118abe69-1b16-49c5-af5b-769a145f91d0",
          "card": "7337dade-5ea7-44f4-8f13-73b7dcbd8677"
        },
        {
          "id": "223de8bb-d696-4dc2-bc31-ba957f4d605f",
          "card": "b7806531-b3f9-4841-a311-e12ac84c5632"
        },
        {
          "id": "f8ebe9cd-8b86-46eb-971c-4309d1381d48",
          "card": "fb5370cc-96f2-4465-9ea6-c6ad31a08f50"
        },
        {
          "id": "cd6099d5-e6cf-4e21-8736-08c021b70c5c",
          "card": "2a527770-1cce-4e44-8dda-0aeba0cdcb86"
        },
        {
          "id": "b1ae4e7d-8338-4c42-a296-aa8c73b8f95a",
          "card": "01fdad9d-76db-4986-88de-6b79960e1779"
        },
        {
          "id": "7d386f3f-20d7-45e0-a1ad-54b7417ee45d",
          "card": "da22a76b-7f7f-4156-9523-4c5fd210fcf1"
        },
        {
          "id": "201388e8-d7e8-4293-b771-1e78199a1f99",
          "card": "ec4a59cb-cebf-4456-a40c-e3ca6fed0455"
        },
        {
          "id": "b6a5fa70-bdb7-4380-8b93-42418f515510",
          "card": "0a69fd52-e4fd-4db8-8483-17222d323990"
        },
        {
          "id": "36aa59ae-3aaf-41ff-b234-f07b703e1a64",
          "card": "5056d3f1-2e7c-4047-bd68-3c1025151c26"
        },
        {
          "id": "8393be6f-7f0d-4fc0-9edc-b8821537654c",
          "card": "f347186c-f2d9-4130-8a7b-9624ec227805"
        },
        {
          "id": "81dd3c27-1a00-427e-bc05-fdb7c84930c5",
          "card": "9df9fdf3-5356-4e99-8ff8-a4015d983f6c"
        },
        {
          "id": "ccadb4a7-247c-4170-9a4e-93d213050861",
          "card": "4d40b367-b9a7-4084-b9cb-37ef3bf2d4cd"
        },
        {
          "id": "96f9b489-2331-421b-9dd8-745f0c73fe17",
          "card": "da1ea7aa-2091-4dd3-ae97-c184bfa8d940"
        },
        {
          "id": "42fa72ac-a3e0-4db9-8164-b5d323c06bf7",
          "card": "0f0430c0-55fc-46f6-b385-48f7dff5bcbf"
        },
        {
          "id": "71e194d3-52b5-4130-982b-08da405de1c3",
          "card": "61c453cf-c3b7-438a-ab3d-4cb607ef9783"
        },
        {
          "id": "0e7f160c-349b-41b9-8b57-dfeb14479151",
          "card": "2c7838be-4f48-4eee-997e-85fa97d2277c"
        },
        {
          "id": "8f1fbdf5-9ac5-41b9-9838-da726c6e936a",
          "card": "fd9d854c-c770-4c49-a631-9922e6ce45dc"
        },
        {
          "id": "b3507a04-cdd4-4567-b272-1c729adb2f1d",
          "card": "a586f0a0-2482-42df-a2de-777555c81783"
        }
      ],
      "externalIDs": {}
    }
  ],
  "externalIDs": {
    "yugipedia": {
      "name": "Deck Build Box: Buster Assault",
      "id": 1136173
    }
  }
}

=== DjobaDELATV/seygo_data/sets/45c5ff37-bb3b-48b3-8fd8-84f83e31af92.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/set.json",
  "id": "45c5ff37-bb3b-48b3-8fd8-84f83e31af92",
  "name": {
    "en": "Duelist Card Protector EX: Master of HERO",
    "ja": "\u30c7\u30e5\u30a8\u30ea\u30b9\u30c8\u30ab\u30fc\u30c9\u30d7\u30ed\u30c6\u30af\u30bf\u30fc \uff25\uff38 \uff3b\uff2d\uff41\uff53\uff54\uff45\uff52 \uff4f\uff46 \uff28\uff25\uff32\uff2f\uff3d \u7279\u5178\u30ab\u30fc\u30c9"
  },
  "locales": {
    "jp": {
      "language": "ja",
      "prefix": "DPEX-JP",
      "date": "2014-06-21",
      "image": "https://ms.yugipedia.com//4/41/DPEX002-PromoJP.png",
      "cardImages": {
        "unlimited": {
          "e4a48eeb-df11-4bdd-8e60-5e7d3c910d27": "https://ms.yugipedia.com//c/c9/ElementalHERONovaMaster-DPEX-JP-NPR.png"
        }
      },
      "cardInfo": {
        "unlimited": {
          "e4a48eeb-df11-4bdd-8e60-5e7d3c910d27": {
            "image": "https://ms.yugipedia.com//c/c9/ElementalHERONovaMaster-DPEX-JP-NPR.png"
          }
        }
      },
      "formats": [
        "ocg"
      ],
      "editions": [
        "unlimited"
      ],
      "externalIDs": {
        "dbIDs": [
          111115000
        ]
      }
    }
  },
  "contents": [
    {
      "locales": [
        "jp"
      ],
      "formats": [
        "ocg"
      ],
      "editions": [
        "unlimited"
      ],
      "image": "https://ms.yugipedia.com//4/41/DPEX002-PromoJP.png",
      "cards": [
        {
          "id": "e4a48eeb-df11-4bdd-8e60-5e7d3c910d27",
          "card": "936836e5-cb0e-4146-b95a-75eb19f4ffa4",
          "suffix": "002",
          "rarity": "commonparallel"
        }
      ],
      "externalIDs": {}
    }
  ],
  "externalIDs": {
    "yugipedia": {
      "name": "Duelist Card Protector EX: Master of HERO",
      "id": 314164
    }
  }
}

=== DjobaDELATV/seygo_data/sets/57cf8ab0-012f-45f1-be0f-b139ee6f901a.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/set.json",
  "id": "57cf8ab0-012f-45f1-be0f-b139ee6f901a",
  "date": "2022-01-19",
  "name": {
    "en": "Essence of Flora and Ocean"
  },
  "contents": [
    {
      "formats": [
        "masterduel"
      ],
      "image": "https://ms.yugipedia.com//f/f4/Essence_of_Flora_and_Ocean-Pack-Master_Duel.png",
      "cards": [
        {
          "id": "95e82d17-cabf-496b-821e-0cca6c69d65f",
          "card": "8bc42c00-6d87-452b-b026-9ad13b3294d1"
        },
        {
          "id": "42f222e5-1d96-4f5b-b879-46ae127cc7dc",
          "card": "9a20ed60-972a-4520-af7f-bd41d10fb85d"
        },
        {
          "id": "cbaa3ec7-893b-44c3-8942-fa4a12392163",
          "card": "2f361dfd-1c37-4bfe-9667-51358c78064f"
        },
        {
          "id": "2ce1499d-02fb-4c2e-a1a0-1f1c0f958ea2",
          "card": "e5b68ca9-e5fb-4c62-bb9a-1952036bc454"
        },
        {
          "id": "0ef088a3-4511-416a-9b0f-c09c8619c1f4",
          "card": "50571601-df56-42e2-b2a5-c601d308e102"
        },
        {
          "id": "e986baba-d7c2-448c-be2b-cfc680c28645",
          "card": "e1857134-947d-41a2-b456-687f66031d7a"
        },
        {
          "id": "d626d7a1-99ec-4327-a2d1-825be1668772",
          "card": "f242f50c-6897-4451-80cd-2015f850c741"
        },
        {
          "id": "c1468f4e-d74a-4b31-b8ec-cdfb922b850a",
          "card": "fef8f6c9-8b92-4566-86c3-4f1b9999583d"
        },
        {
          "id": "7068c360-a262-4809-83de-a95d3245178a",
          "card": "949d24de-b797-4526-a9c0-b7bc7210d442"
        },
        {
          "id": "4468bae2-25f2-4b2d-b18e-8b2c339293fa",
          "card": "010eb61d-34fc-4bd8-be2f-1bb2e942ac48"
        },
        {
          "id": "c16baed0-bc69-46fa-8d0c-e6d377f0984e",
          "card": "2b5145c5-74ad-44c8-9df2-ba720874604a"
        },
        {
          "id": "5a6db4ff-f88c-40a4-93b0-568b9049489b",
          "card": "9dcb6990-bae0-4308-81f4-51dbe5ad6b31"
        },
        {
          "id": "5fe6f12f-d901-41ef-b682-1ac4b9f59b0b",
          "card": "1a968672-28fb-492f-be4c-13f0125745d7"
        },
        {
          "id": "284c1dde-b109-44e8-96d9-018f95e21eb4",
          "card": "90076f2b-04b7-4039-bbc5-a6a9dc0f4947"
        },
        {
          "id": "67cc84fd-325c-4c32-884c-48c2b9266eb3",
          "card": "b06a2803-fe69-4849-8b70-5fd157b3d932"
        },
        {
          "id": "8c4f8c41-3481-447d-857d-d76f60dc85b2",
          "card": "ded7f530-c103-4186-9848-2869da89ba1a"
        },
        {
          "id": "d4679886-9909-4b29-ae9a-79e29970ac19",
          "card": "cefce943-c70f-46e7-b44d-235bbe26acd4"
        },
        {
          "id": "60bdb628-de0f-4cae-8e25-2de5b6b8de59",
          "card": "ca18231f-dac3-487c-b6ba-4ad21fcc2df1"
        },
        {
          "id": "1fdb0c0f-79ba-4430-a609-94ac9b8a0a90",
          "card": "70aed5af-626b-4ed6-ba95-14ba88243711"
        },
        {
          "id": "cddbe04f-94bd-44de-af66-4457d5af5cc2",
          "card": "8e175742-9d79-4964-a3e3-3730647e8397"
        },
        {
          "id": "c8bcb4f4-8ea2-4f6c-856c-2fcb27b3aae2",
          "card": "72edc12b-b8f8-46ad-b305-3fb48540920d"
        },
        {
          "id": "386821e7-0418-4a0c-9fe2-39416e4c35d1",
          "card": "2e006836-41ea-401a-9be8-3bb0c2044979"
        },
        {
          "id": "850659da-70cf-41a8-a12d-538afeb25bb4",
          "card": "9b9b0cbc-e80d-460d-8196-a6f6ab9c72fb"
        },
        {
          "id": "47604126-f261-47d7-9981-6a0b3b03bade",
          "card": "02e533f8-b99f-4f77-bac7-290735b2469f"
        },
        {
          "id": "6ae6cd9b-f8b2-41e5-9dee-7cbf48fc0817",
          "card": "a622762c-8885-47b3-b4a2-b9398b076782"
        },
        {
          "id": "a96389e9-1e0b-495d-a04d-6a338d20afd3",
          "card": "2c500121-c3e1-46c9-900e-6d4c60f2be8b"
        },
        {
          "id": "55adfdf8-adf5-4592-929b-23cfba05487d",
          "card": "ed7fcd01-cf3d-4af5-9f06-52adb492cabf"
        },
        {
          "id": "34e0dcc5-08b7-4700-883c-01b9ebb5ed28",
          "card": "6f6ff397-4caa-4e4b-ab18-ac0b1984861e"
        },
        {
          "id": "effdbde6-9978-47ae-9997-3461a174e722",
          "card": "077532e9-db06-49b0-9380-b49654d44afd"
        },
        {
          "id": "809e7cbb-3b15-48e2-b73d-881dc7b05f22",
          "card": "958a772a-7ea2-43a9-855b-ec77c24a9782"
        },
        {
          "id": "2f97a312-a103-4299-b2da-4992b963e0db",
          "card": "70953206-82c7-4b1e-aacf-70a3fb69135a"
        },
        {
          "id": "a1621bf1-4682-4031-9176-131b14f5bd67",
          "card": "f288082f-463d-4ddc-8f24-86a885925c66"
        },
        {
          "id": "462bca09-bb28-46a1-9a79-f850467f5b0d",
          "card": "d8efc223-f63e-4321-9d4c-396d942ef537"
        },
        {
          "id": "27b3fd1f-5988-4d59-b299-9bffde047441",
          "card": "71fd65a2-a3b7-4b07-98da-c41322be389e"
        },
        {
          "id": "3673d25d-37b9-407d-97f9-5568bda9e5b2",
          "card": "8961cd53-9a60-4d4f-bc56-6f0c59f5aa21"
        },
        {
          "id": "3ec70d7a-9433-455e-87db-a436cef244fa",
          "card": "70622885-a9a7-4f32-99ba-6994a3a3eda8"
        },
        {
          "id": "4cb2546c-0224-4b38-903c-011a4c833817",
          "card": "d730d189-ff0c-4558-a072-ec003b795ac3"
        },
        {
          "id": "1588017b-ca89-4128-ba9a-2710354468bc",
          "card": "08b511ce-ecbc-4a2d-b03e-62b3f9617250"
        },
        {
          "id": "4349175a-51b0-46a1-b109-27a87e779dc5",
          "card": "8a56fe04-8d31-47de-820b-ebbdb9318fda"
        },
        {
          "id": "841b7b08-c4b4-42a3-9f58-b9d4700d1f31",
          "card": "b7c3f631-8775-44e1-8940-0a7854c17f96"
        },
        {
          "id": "bb01798c-2ba9-4916-aa43-f840103dc7c0",
          "card": "75c682e7-c26e-4e06-80e3-eea6c0decf50"
        },
        {
          "id": "c31e8261-ac47-42cb-8cac-3a6a61a33b89",
          "card": "0280e055-97f7-4c61-8777-3cedd64d572a"
        },
        {
          "id": "c2b4ca2f-d655-44c8-9e2e-77899ebce944",
          "card": "edbde91e-b234-418c-8668-df3e5cc666fd"
        },
        {
          "id": "3a93b451-cc18-4046-8ba4-17f14c9be4ea",
          "card": "4dfb0608-99f7-4377-8a05-c0ebc603d33a"
        },
        {
          "id": "de08dd63-49e7-43a1-adcb-53074b0fe6d4",
          "card": "b34c64d7-8c0c-4f12-a893-f99fc8bd8400"
        },
        {
          "id": "3a965008-0d47-435e-a326-9cb1b976b1a7",
          "card": "efc32683-8c69-4372-b39f-b8861ff5bd7e"
        },
        {
          "id": "5601664a-e172-43cd-8321-0cad65c0b433",
          "card": "0afb170c-d56f-4aa4-83a6-2dcba8d82839"
        },
        {
          "id": "349822b6-f1b4-48c1-a8bf-9e26a8b14eb4",
          "card": "4b1d8c7b-8453-496b-bdd0-5fe89c7f9a41"
        },
        {
          "id": "d3428965-fb61-4bf5-ac44-9f135b001c0f",
          "card": "260b1a31-5ce5-448f-8ee5-a403966ade23"
        },
        {
          "id": "f204d72c-e489-411b-872f-2820fc0d073b",
          "card": "3421a33a-e253-4a41-9f53-1dca78d3a384"
        },
        {
          "id": "9c7f8119-8c09-4c00-89e0-a054951c7403",
          "card": "686d356e-885b-4deb-8db3-05702a93d551"
        },
        {
          "id": "f45fef30-af6a-484a-8d61-26170ec23871",
          "card": "911a51bf-4b5b-40a6-b8c3-60b31591fc72"
        },
        {
          "id": "bd54dabc-60ee-49d5-bc3a-529296d17b99",
          "card": "c19d5040-71f6-4bdb-9f52-0fe3d4ab2941"
        },
        {
          "id": "a7bb3283-d8c3-4709-8e99-be484ea68ba2",
          "card": "0f5250a5-07b5-4966-9750-4068eeb64c56"
        },
        {
          "id": "4953b70f-805a-474f-a18d-1c03a58a3462",
          "card": "b902d48a-3884-4f04-902b-902b83e573d4"
        }
      ],
      "externalIDs": {}
    }
  ],
  "externalIDs": {
    "yugipedia": {
      "name": "Essence of Flora and Ocean",
      "id": 904023
    }
  }
}
