=== DjobaDELATV/seygo_data/schema/v1/skill.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "title": "Skill",
  "description": "A Duel Links Skill (not a physical card).",
  "type": "object",
  "required": [
    "$schema",
    "id",
    "text",
    "cardType"
  ],
  "properties": {
    "$schema": {
      "const": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json"
    },
    "id": {
      "description": "The UUID of this skill.",
      "type": "string",
      "format": "uuid"
    },
    "text": {
      "description": "A map of languages to textual skill information.",
      "type": "object",
      "additionalProperties": {
        "description": "Textual information on the skill.",
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "description": "The name of the skill.",
            "type": "string"
          },
          "effect": {
            "description": "The effect text of the skill.",
            "type": "string"
          },
          "official": {
            "description": "Is this translation official?",
            "type": "boolean"
          }
        }
      }
    },
    "cardType": {
      "description": "Always 'skill-dl' for Duel Links skills.",
      "const": "skill-dl"
    },
    "skillType": {
      "description": "The type of skill (Legendary, Archive).",
      "type": "string"
    },
    "supports": {
      "description": "List of card names this skill supports or mentions.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "supportsArchetypes": {
      "description": "List of archetypes this skill supports.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "releases": {
      "description": "How this skill can be obtained.",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "character",
          "type"
        ],
        "properties": {
          "character": {
            "description": "The character associated with this release.",
            "type": "string"
          },
          "type": {
            "description": "The release type (duel_reward, level_up, trader, etc.).",
            "type": "string"
          },
          "details": {
            "description": "Additional details (e.g., 'Level 20').",
            "type": "string"
          }
        }
      }
    },
    "externalIDs": {
      "description": "IDs from external sources.",
      "type": "object",
      "properties": {
        "yugipedia": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "id": {
                "type": "integer"
              }
            }
          }
        }
      }
    }
  }
}

=== DjobaDELATV/seygo_data/skills/7a80f8b7-03ff-4495-98a9-c10379306ea3.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "7a80f8b7-03ff-4495-98a9-c10379306ea3",
  "text": {
    "en": {
      "name": "I Rule Over Every Dragon",
      "effect": "Can be used when the only monsters on your field are 2 Dragon-Type LIGHT monsters.\nAll the monsters on your field are set to Level 8 until the end of the turn.\nOn the turn you use this Skill, you can only Special Summon Rank 8/9 Dragon-Type LIGHT Xyz Monsters. If you set a Deck that fulfills the following conditions and begin the Duel, this Skill can only be used once per Duel.\n* Monsters in your Deck are only Dragon-Type monsters.\n* Monsters in your Extra Deck are only Dragon-Type Xyz Monsters."
    },
    "fr": {
      "name": "Je suis le Ma\u00eetre de tous les Dragons",
      "effect": "Utilisable seulement si les seuls monstres sur votre Terrain sont 2 monstres de Type Dragon LUMI\u00c8RE.\nLe Niveau de tous les monstres sur votre Terrain passe \u00e0 8 jusqu'\u00e0 la fin du tour.\nLors du tour pendant lequel vous utilisez cette Comp\u00e9tence, vous pouvez uniquement Invoquer Sp\u00e9cialement des Monstres Xyz de Type Dragon LUMI\u00c8RE de Rang 8 et 9.\nSi vous cr\u00e9ez un Deck qui remplit les conditions suivantes et que vous commencez le Duel, cette Comp\u00e9tence ne peut \u00eatre utilis\u00e9e qu'une fois par Duel.\n* Votre Deck ne contient que des monstres de Type Dragon.\n* Votre Extra Deck ne contient que des Monstres Xyz de Type Dragon."
    },
    "ja": {
      "name": "\u6700\u5f37\u306e\u30c9\u30e9\u30b4\u30f3\u4f7f\u3044\u306f\u3053\u306e\u79c1\u3060",
      "effect": "\u81ea\u5206\u30d5\u30a3\u30fc\u30eb\u30c9\u306e\u30e2\u30f3\u30b9\u30bf\u30fc\u304c\u30c9\u30e9\u30b4\u30f3\u65cf\u30fb\u5149\u5c5e\u6027\u30e2\u30f3\u30b9\u30bf\u30fc\uff12\u4f53\u306e\u307f\u306e\u5834\u5408\u306b\u4f7f\u7528\u3067\u304d\u308b\u3002\u81ea\u5206\u30d5\u30a3\u30fc\u30eb\u30c9\u306e\u30e2\u30f3\u30b9\u30bf\u30fc\u5168\u3066\u306e\u30ec\u30d9\u30eb\u3092\u30bf\u30fc\u30f3\u7d42\u4e86\u6642\u307e\u3067\uff18\u306b\u3059\u308b\u3002\u3053\u306e\u30b9\u30ad\u30eb\u3092\u4f7f\u7528\u3057\u305f\u30bf\u30fc\u30f3\u3001\u81ea\u5206\u306f\u30e9\u30f3\u30af\uff18\u30fb\uff19\u306e\u30c9\u30e9\u30b4\u30f3\u65cf\u30fb\u5149\u5c5e\u6027\u30a8\u30af\u30b7\u30fc\u30ba\u30e2\u30f3\u30b9\u30bf\u30fc\u3057\u304b\u7279\u6b8a\u53ec\u559a\u3067\u304d\u306a\u3044\u3002\u3053\u306e\u30b9\u30ad\u30eb\u306f\u4ee5\u4e0b\u306e\u6761\u4ef6\u3092\u6e80\u305f\u3057\u305f\u30c7\u30c3\u30ad\u3092\u8a2d\u5b9a\u3057\u3066\u30c7\u30e5\u30a8\u30eb\u3092\u958b\u59cb\u3057\u305f\u5834\u5408\u306b\u3001\u30c7\u30e5\u30a8\u30eb\u4e2d\uff11\u5ea6\u306e\u307f\u4f7f\u7528\u3067\u304d\u308b\u3002\n\u25cf\u30c7\u30c3\u30ad\u306e\u30e2\u30f3\u30b9\u30bf\u30fc\u304c\u30c9\u30e9\u30b4\u30f3\u65cf\u30e2\u30f3\u30b9\u30bf\u30fc\u306e\u307f\n\u25cf\u30a8\u30af\u30b9\u30c8\u30e9\u30c7\u30c3\u30ad\u306e\u30e2\u30f3\u30b9\u30bf\u30fc\u304c\u30c9\u30e9\u30b4\u30f3\u65cf\u306e\u30a8\u30af\u30b7\u30fc\u30ba\u30e2\u30f3\u30b9\u30bf\u30fc\u306e\u307f"
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "supports": [
    "LIGHT",
    "Dragon",
    "Xyz Monster"
  ],
  "releases": [
    {
      "character": "Mizar (Duel Links)",
      "type": "duel_reward"
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "I Rule Over Every Dragon",
        "id": 1041817
      }
    ]
  }
}

=== DjobaDELATV/seygo_data/skills/06f4350c-af4f-4a87-9be6-a112faf4a55e.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "06f4350c-af4f-4a87-9be6-a112faf4a55e",
  "text": {
    "en": {
      "name": "Burst Trigger",
      "effect": "1: At the beginning of your first turn, add 1 \"Polymerization\" from outside your Deck to your hand. During this Duel, you can only Fusion Summon \"Blue-Eyes\" Fusion Monsters."
    },
    "fr": {
      "name": "Amorce Explosive",
      "effect": "1 : Au d\u00e9but de votre premier tour, ajoutez 1 \"Polym\u00e9risation\" \u00e0 votre main depuis l'ext\u00e9rieur de votre Deck. Pendant ce Duel, vous ne pouvez Invoquer par Fusion que des Monstres Fusion \"Yeux Bleus\"."
    },
    "ja": {
      "name": ""
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "supports": [
    "Polymerization (Duel Links)",
    "Fusion Monster"
  ],
  "supportsArchetypes": [
    "Blue-Eyes"
  ],
  "releases": [
    {
      "character": "Seto Kaiba (Duel Links)",
      "type": "box",
      "details": "Character Deck (Kaiba Deck)"
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Burst Trigger",
        "id": 1182982
      }
    ]
  }
}

=== DjobaDELATV/seygo_data/skills/13e2ce22-3f33-4c10-9330-c23260ea5d78.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "13e2ce22-3f33-4c10-9330-c23260ea5d78",
  "text": {
    "en": {
      "name": "Bear Parade",
      "effect": "Each of the following effects can be used once per turn and once per Duel by selecting 1 \"Frightfur Bear\" you control.\n* Select 1 monster in your opponent's Graveyard and equip it to this card as an Equip Card. The card equipped counts as having been equipped by the effect of this \"Frightfur Bear\".\n* During this turn, the selected monster gains an additional attack for each card it has equipped."
    },
    "fr": {
      "name": "Parade de l'ours",
      "effect": "Chacun des effets suivants peut \u00eatre utilis\u00e9 une fois par tour et une fois par Duel en s\u00e9lectionnant 1 \"Ours Frourreur\" que vous contr\u00f4lez.\n* S\u00e9lectionnez 1 monstre dans le Cimeti\u00e8re de votre adversaire et \u00e9quipez-le \u00e0 cette carte en tant que Carte d'\u00c9quipement. La carte \u00e9quip\u00e9e compte comme ayant \u00e9t\u00e9 \u00e9quip\u00e9e par l'effet de cette Carte \"Ours Frourreur\".\n* Lors de ce tour, le monstre s\u00e9lectionn\u00e9 gagne une attaque suppl\u00e9mentaire pour chaque carte qu'il a \u00e9quip\u00e9e."
    },
    "ja": {
      "name": ""
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "supports": [
    "Frightfur Bear (Duel Links)"
  ],
  "releases": [
    {
      "character": "Sora Perse (Duel Links)",
      "type": "level_up",
      "details": "Level 20"
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Bear Parade",
        "id": 713584
      }
    ]
  }
}

=== DjobaDELATV/seygo_data/skills/b7eb4338-761c-447d-9012-6053d31d1520.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "b7eb4338-761c-447d-9012-6053d31d1520",
  "text": {
    "en": {
      "name": "Draw Sense: LIGHT",
      "effect": "Can be used before your normal draw each time your Life Points decrease by 1500. One of the cards from your normal draw this turn will be a random LIGHT monster in your Deck."
    },
    "fr": {
      "name": "Pioche de LUMI\u00c8RE",
      "effect": "Cette Comp\u00e9tence peut \u00eatre utilis\u00e9e avant votre pioche normale \u00e0 chaque fois que vos Life Points diminuent de 1 500. L'une des cartes de votre pioche normale de ce tour sera un monstre LUMI\u00c8RE al\u00e9atoire de votre Deck."
    },
    "ja": {
      "name": "\u30c9\u30ed\u30fc\u30bb\u30f3\u30b9\uff1a\u5149",
      "effect": "\u81ea\u5206\u306e\u30e9\u30a4\u30d5\u30dd\u30a4\u30f3\u30c8\u304c\uff11\uff15\uff10\uff10\u6e1b\u308b\u6bce\u306b\u4f7f\u7528\u3067\u304d\u308b\u3002\u30c9\u30ed\u30fc\u30d5\u30a7\u30a4\u30ba\u6642\u306b\u901a\u5e38\u306e\u30c9\u30ed\u30fc\u3092\u884c\u3046\u304b\u308f\u308a\u306b\u3001\u30e9\u30f3\u30c0\u30e0\u3067\u5149\u5c5e\u6027\u30e2\u30f3\u30b9\u30bf\u30fc\u3092\u30c9\u30ed\u30fc\u3059\u308b\u3002"
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "supports": [
    "LIGHT"
  ],
  "releases": [
    {
      "character": "Seto Kaiba (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Yugi Muto (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "T\u00e9a Gardner (Duel Links)",
      "type": "mission",
      "details": "Normal or Special Summon a LIGHT Monster 4 time(s) in one Duel using T\u00e9a Gardner."
    },
    {
      "character": "Ishizu Ishtar (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Odion (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Maximillion Pegasus (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Mokuba Kaiba (Duel Links)",
      "type": "level_up",
      "details": "Level 20"
    },
    {
      "character": "Paradox Brothers (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Duke Devlin (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Rebecca Hawkins (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Seto Kaiba (DSOD) (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Mokuba Kaiba (DSOD) (Duel Links)",
      "type": "level_up",
      "details": "Level 13"
    },
    {
      "character": "Sera (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Jaden Yuki (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Zane Truesdale (Duel Links)",
      "type": "level_up",
      "details": "Level 4"
    },
    {
      "character": "Aster Phoenix (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Jesse Anderson (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Chazz Princeton (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Dr. Vellian Crowler (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Bastion Misawa (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Sartorius Kumar (Duel Links)",
      "type": "level_up",
      "details": "Level 13"
    },
    {
      "character": "Jaden/Yubel",
      "type": "duel_reward"
    },
    {
      "character": "Blair Flannigan (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Luna (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Dark Signer Rex Goodwin",
      "type": "duel_reward"
    },
    {
      "character": "Sherry LeBlanc (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Z-one (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Tori Meadows (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Kite Tenjo (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Trey (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Quinton (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Mizar (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Dumon (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Zuzu Boyle (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Dennis McField (Duel Links)",
      "type": "duel_reward"
    },
    {
      "character": "Blue Angel (Duel Links)",
      "type": "level_up",
      "details": "Level 13"
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Draw Sense: LIGHT",
        "id": 714690
      }
    ]
  }
}

=== DjobaDELATV/seygo_data/skills/10fbe005-f7a2-46c3-9819-413897ffdbd8.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "10fbe005-f7a2-46c3-9819-413897ffdbd8",
  "text": {
    "en": {
      "name": "Fossil Warriors",
      "effect": "At the beginning of the Duel, add 1 \"Weathering Soldier\", 1 \"Gaia Plate the Earth Giant\", and 1 \"Fossil Fusion\" to your Deck and 1 \"Fossil Warrior Skull King\", 1 \"Fossil Warrior Skull Knight\", and 1 \"Fossil Warrior Skull Bone\" to your Extra Deck.\nCan be used if your Life Points are at 2000 or below. Send 1 Rock-Type monster in your hand to the Graveyard and add 1 \"Fossil Fusion\" to your hand from your Deck or Graveyard.\nThis Skill can only be used once per Duel."
    },
    "fr": {
      "name": "Guerriers Fossiles",
      "effect": "Au d\u00e9but du Duel, ajoutez 1 \"Soldat M\u00e9t\u00e9o\", 1 \"Gaia, G\u00e9ant de Terre\" et 1 \"Fusion Fossile\" \u00e0 votre Deck, ainsi que 1 \"Guerrier Fossile Chevalier Squelette\" et 1 \"Guerrier Fossile Monstre Squelette\" \u00e0 votre Extra Deck.\nCette Comp\u00e9tence peut \u00eatre utilis\u00e9e si vos Life Points sont de 2 000 ou moins. Envoyez 1 monstre de Type Rocher de votre main au Cimeti\u00e8re et ajoutez 1 \"Fusion Fossile\" depuis votre Deck ou votre Cimeti\u00e8re dans votre main.\nCette Comp\u00e9tence ne peut \u00eatre utilis\u00e9e qu'une fois par Duel."
    },
    "ja": {
      "name": "\u53e4\u751f\u4ee3\u306e\u5316\u77f3\u9a0e\u58eb",
      "effect": "\u30c7\u30e5\u30a8\u30eb\u958b\u59cb\u6642\u306b\u3001\u81ea\u5206\u306e\u30c7\u30c3\u30ad\u306b\u300c\u98a8\u5316\u6226\u58eb\u300d\u300c\u5730\u7403\u5de8\u4eba\u30ac\u30a4\u30a2\u30fb\u30d7\u30ec\u30fc\u30c8\u300d\u300c\u5316\u77f3\u878d\u5408\u30d5\u30a9\u30c3\u30b7\u30eb\u30fb\u30d5\u30e5\u30fc\u30b8\u30e7\u30f3\u300d\u3092\uff11\u679a\u305a\u3064\u3001\u81ea\u5206\u306e\u30a8\u30af\u30b9\u30c8\u30e9\u30c7\u30c3\u30ad\u306b\u300c\u53e4\u751f\u4ee3\u5316\u77f3\u9a0e\u58eb\u30b9\u30ab\u30eb\u30ad\u30f3\u30b0\u300d\u300c\u4e2d\u751f\u4ee3\u5316\u77f3\u9a0e\u58eb\u30b9\u30ab\u30eb\u30ca\u30a4\u30c8\u300d\u300c\u65b0\u751f\u4ee3\u5316\u77f3\u9a0e\u58eb\u30b9\u30ab\u30eb\u30dd\u30fc\u30f3\u300d\u3092\uff11\u679a\u305a\u3064\u8ffd\u52a0\u3059\u308b\u3002\n\u307e\u305f\u3001\u81ea\u5206\u306e\u30e9\u30a4\u30d5\u30dd\u30a4\u30f3\u30c8\u304c\uff12\uff10\uff10\uff10\u4ee5\u4e0b\u306e\u6642\u306b\u4f7f\u7528\u3067\u304d\u308b\u3002\u624b\u672d\u306e\u5ca9\u77f3\u65cf\u30e2\u30f3\u30b9\u30bf\u30fc\uff11\u679a\u3092\u5893\u5730\u3078\u9001\u308a\u3001\u30c7\u30c3\u30ad\u30fb\u5893\u5730\u304b\u3089\u300c\u5316\u77f3\u878d\u5408\u30d5\u30a9\u30c3\u30b7\u30eb\u30fb\u30d5\u30e5\u30fc\u30b8\u30e7\u30f3\u300d\uff11\u679a\u3092\u624b\u672d\u306b\u52a0\u3048\u308b\u3002\n\u3053\u306e\u30b9\u30ad\u30eb\u306f\u30c7\u30e5\u30a8\u30eb\u4e2d\u306b\uff11\u5ea6\u306e\u307f\u4f7f\u7528\u3067\u304d\u308b\u3002"
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "supports": [
    "Weathering Soldier (Duel Links)",
    "Gaia Plate the Earth Giant (Duel Links)",
    "Fossil Fusion (Duel Links)",
    "Fossil Warrior Skull King (Duel Links)",
    "Fossil Warrior Skull Knight (Duel Links)",
    "Fossil Warrior Skull Bone (Duel Links)"
  ],
  "releases": [
    {
      "character": "Jim \"Crocodile\" Cook (Duel Links)",
      "type": "level_up",
      "details": "Level 1"
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Fossil Warriors",
        "id": 715011
      }
    ]
  }
}

=== DjobaDELATV/seygo_data/skills/782e4660-1b00-42b3-afc8-6fb5ebddcac4.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "782e4660-1b00-42b3-afc8-6fb5ebddcac4",
  "text": {
    "en": {
      "name": "HERO Alliance",
      "effect": "During this Duel, you can Normal Summon/Set \"Elemental HERO Neos\" without Tributing.\n\nIn addition, the following effect can be used once per Duel, on a turn when you have Summoned \"Elemental HERO Neos.\" Send 1 card from your hand to the Graveyard and add 1 \"Super Polymerization\" in your Deck or 1 \"Polymerization,\" \"Miracle Contact,\" or \"Miracle Fusion\" from outside of your Deck to your hand. Then, send 2 random \"Neo-Spacian\" monsters from outside of your Deck to the Graveyard and add \"Elemental HERO Divine Neos\" to your Extra Deck.\nThis Skill can only be used/applied if you begin the Duel with a Deck that follows the conditions below.\n* Your Deck contains at least 10 \"HERO\" monsters and no \"HERO\" monsters other than \"Elemental HERO\" monsters\n* Your Extra Deck contains at least 5 Fusion Monsters and contains no Fusion Monsters other than \"Elemental HERO,\" \"Neos\", or \"Neo-Spacian\" monsters."
    },
    "fr": {
      "name": "Alliance de H\u00c9ROS",
      "effect": "Lors de ce Duel, vous pouvez Invoquer Normalement/Poser \"N\u00e9os, H\u00c9ROS \u00c9l\u00e9mentaire\" sans Sacrifice.\nDe plus, une fois par Duel, l'effet suivant peut \u00eatre utilis\u00e9 le tour o\u00f9 vous avez Invoqu\u00e9 Normalement \"N\u00e9os, H\u00c9ROS \u00c9l\u00e9mentaire\". Ajoutez 1 \"Super Polym\u00e9risation\" depuis votre Deck, ou 1 \"Polym\u00e9risation\", \"Contact Miracle\" ou \"Fusion Miraculeuse\" depuis l'ext\u00e9rieur de votre Deck \u00e0 votre main. Ensuite, envoyez 2 des 6 monstres \"N\u00e9o-Spacien\" al\u00e9atoires diff\u00e9rents depuis l'ext\u00e9rieur de votre Deck au Cimeti\u00e8re et ajoutez \"N\u00e9os Divin, H\u00c9ROS \u00c9l\u00e9mentaire\" \u00e0 votre Extra Deck depuis l'ext\u00e9rieur de votre Deck.\nCette Comp\u00e9tence ne s'activera que si vous commencez le Duel avec un Deck respectant les conditions ci-dessous.\n* Votre Deck contient au moins 10 monstres \"H\u00c9ROS\", et uniquement des monstres \"H\u00c9ROS \u00c9l\u00e9mentaire\".\n* Votre Extra Deck contient au moins 5 Monstres Fusion et ne contient aucun Monstre Fusion autre que des monstres \"H\u00c9ROS \u00c9l\u00e9mentaire\", \"N\u00e9os\" et \"N\u00e9o-Spacien\"."
    },
    "ja": {
      "name": "\uff28\uff25\uff32\uff2f\u3068\u306e\u7d46",
      "effect": "\u3053\u306e\u30c7\u30e5\u30a8\u30eb\u4e2d\u3001\u81ea\u5206\u306f\u300c\uff25\u30fb\uff28\uff25\uff32\uff2f \u30cd\u30aa\u30b9\u300d\u3092\u901a\u5e38\u53ec\u559a\u3059\u308b\u5834\u5408\u306b\u5fc5\u8981\u306a\u30ea\u30ea\u30fc\u30b9\u304c\u7121\u304f\u306a\u308b\u3002\n\u307e\u305f\u30c7\u30e5\u30a8\u30eb\u4e2d\uff11\u5ea6\u3001\u81ea\u5206\u304c\u300c\uff25\u30fb\uff28\uff25\uff32\uff2f \u30cd\u30aa\u30b9\u300d\u3092\u53ec\u559a\u3057\u305f\u30bf\u30fc\u30f3\u306b\u4f7f\u7528\u3067\u304d\u308b\u3002\u624b\u672d\u3092\u5893\u5730\u3078\u9001\u308a\u3001\u30c7\u30c3\u30ad\u306e\u300c\u8d85\u878d\u5408\u300d\u307e\u305f\u306f\u30c7\u30c3\u30ad\u5916\u306e\u3001\u300c\u878d\u5408\u300d\u300c\u30df\u30e9\u30af\u30eb\u30fb\u30b3\u30f3\u30bf\u30af\u30c8\u300d\u300c\u30df\u30e9\u30af\u30eb\u30fb\u30d5\u30e5\u30fc\u30b8\u30e7\u30f3\u300d\u306e\u5185\u3001\u3044\u305a\u308c\u304b\uff11\u679a\u3092\u624b\u672d\u306b\u52a0\u3048\u308b\u3002\u305d\u306e\u5f8c\u3001\u30c7\u30c3\u30ad\u5916\u304b\u3089\u3001\u30e9\u30f3\u30c0\u30e0\u306b\u300c\uff2e\u300d\u30e2\u30f3\u30b9\u30bf\u30fc\uff12\u679a\u3092\u5893\u5730\u3078\u9001\u308a\u3001\u300c\uff25\u30fb\uff28\uff25\uff32\uff2f \u30b4\u30c3\u30c9\u30fb\u30cd\u30aa\u30b9\u300d\u3092\u30a8\u30af\u30b9\u30c8\u30e9\u30c7\u30c3\u30ad\u306b\u8ffd\u52a0\u3059\u308b\u3002\n\u3053\u306e\u30b9\u30ad\u30eb\u306f\u4ee5\u4e0b\u306e\u6761\u4ef6\u3092\u6e80\u305f\u3057\u305f\u30c7\u30c3\u30ad\u3092\u8a2d\u5b9a\u3057\u3066\u30c7\u30e5\u30a8\u30eb\u3092\u958b\u59cb\u3057\u305f\u5834\u5408\u306b\u4f7f\u7528\u3068\u9069\u7528\u304c\u3067\u304d\u308b\u3002\n\u25cf\u300c\uff28\uff25\uff32\uff2f\u300d\u30e2\u30f3\u30b9\u30bf\u30fc\u304c\uff11\uff10\u679a\u4ee5\u4e0a\u5b58\u5728\u3057\u3001\u305d\u306e\u5168\u3066\u304c\u300c\uff25\u30fb\uff28\uff25\uff32\uff2f\u300d\u30e2\u30f3\u30b9\u30bf\u30fc\u306e\u30c7\u30c3\u30ad\n\u25cf\u878d\u5408\u30e2\u30f3\u30b9\u30bf\u30fc\u304c\uff15\u679a\u4ee5\u4e0a\u5b58\u5728\u3057\u3001\u305d\u306e\u5168\u3066\u304c\u300c\uff25\u30fb\uff28\uff25\uff32\uff2f\u300d\u3001\u300c\u30cd\u30aa\u30b9\u300d\u3001\u300c\uff2e\u300d\u30e2\u30f3\u30b9\u30bf\u30fc\u306e\u30a8\u30af\u30b9\u30c8\u30e9\u30c7\u30c3\u30ad"
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "supports": [
    "Elemental HERO Divine Neos (Duel Links)",
    "Elemental HERO Neos (Duel Links)",
    "Miracle Contact (Duel Links)",
    "Miracle Fusion (Duel Links)",
    "Neo-Spacian Air Hummingbird (Duel Links)",
    "Neo-Spacian Aqua Dolphin (Duel Links)",
    "Neo-Spacian Dark Panther (Duel Links)",
    "Neo-Spacian Flare Scarab (Duel Links)",
    "Neo-Spacian Glow Moss (Duel Links)",
    "Neo-Spacian Grand Mole (Duel Links)",
    "Neo-Spacian Marine Dolphin (Duel Links)",
    "Neo-Spacian Twinkle Moss (Duel Links)",
    "Polymerization (Duel Links)",
    "Super Polymerization (Duel Links)"
  ],
  "supportsArchetypes": [
    "Elemental HERO",
    "Fusion (archetype)",
    "Neos",
    "Neo-Spacian",
    "Polymerization (archetype)"
  ],
  "releases": [
    {
      "character": "Jaden Yuki (Duel Links)",
      "type": "mission",
      "details": "Perform 10 Fusion Summons using Jaden Yuki."
    },
    {
      "character": "Jaden/Yubel",
      "type": "mission",
      "details": "Perform 10 Fusion Summons using Jaden/Yubel."
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "HERO Alliance",
        "id": 715231
      }
    ]
  }
}

=== DjobaDELATV/seygo_data/skills/77eff1eb-13c5-4d21-b58b-08c1e0eb3914.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "77eff1eb-13c5-4d21-b58b-08c1e0eb3914",
  "text": {
    "en": {
      "name": "Destiny Calling",
      "effect": "Can be used after your Life Points are at 3000 or below.\nPlay the Field Spell \"Dark City.\" If there already is Field Spell on your side of the field, return it to your hand.\nThis Skill can only be used once per Duel."
    },
    "fr": {
      "name": "Appel de la Destin\u00e9e",
      "effect": "Cette Comp\u00e9tence ne peut \u00eatre utilis\u00e9e que si vos Life Points sont de 3 000 ou moins.\nJouez la Magie de Terrain \"Ville T\u00e9n\u00e9breuse\". S'il y a d\u00e9j\u00e0 une Magie de Terrain sur votre Terrain, renvoyez-l\u00e0 dans votre main.\nCette Comp\u00e9tence ne peut \u00eatre utilis\u00e9e qu'une fois par Duel."
    },
    "ja": {
      "name": "\u904b\u547d\u306e\u30b9\u30c6\u30fc\u30b8",
      "effect": "\u81ea\u5206\u306e\u30e9\u30a4\u30d5\u30dd\u30a4\u30f3\u30c8\u304c\uff13\uff10\uff10\uff10\u4ee5\u4e0b\u306b\u306a\u3063\u305f\u5f8c\u306b\uff11\u5ea6\u3060\u3051\u4f7f\u7528\u3067\u304d\u308b\u3002\u300c\u30c0\u30fc\u30af\u30fb\u30b7\u30c6\u30a3\u300d\u3092\u767a\u52d5\u3059\u308b\u3002\u81ea\u5206\u30d5\u30a3\u30fc\u30eb\u30c9\u4e0a\u306b\u30d5\u30a3\u30fc\u30eb\u30c9\u9b54\u6cd5\u304c\u5b58\u5728\u3057\u3066\u3044\u308b\u5834\u5408\u3001\u305d\u306e\u30ab\u30fc\u30c9\u306f\u624b\u672d\u306b\u623b\u308b\u3002"
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "supports": [
    "Dark City (Duel Links)",
    "Field Spell Card"
  ],
  "releases": [
    {
      "character": "Aster Phoenix (Duel Links)",
      "type": "level_up",
      "details": "Level 4"
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Destiny Calling",
        "id": 714523
      }
    ]
  }
}

=== DjobaDELATV/seygo_data/skills/984697b8-3481-4781-b446-4c0c71dfb161.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "984697b8-3481-4781-b446-4c0c71dfb161",
  "text": {
    "en": {
      "name": "Marincess Transcend",
      "effect": "Send 1 \"Marincess\" Effect Monster you control to the Graveyard, and add 1 \"Marincess\" monster to your hand from the Deck that is 1 Level higher than the original Level of the monster sent to the Graveyard.During this turn, you cannot Normal or Special Summon any monsters except \"Marincess\" monsters.This Skill can only be used if you begin the Duel with a Deck/Extra Deck that contains no monsters other than WATER Cyberse-Type monsters. This Skill can only be used once per Duel."
    },
    "fr": {
      "name": "Transcendance de Marincesse",
      "effect": "Envoyez 1 Monstre \u00e0 Effet \"Marincesse\" que vous contr\u00f4lez dans votre Cimeti\u00e8re et ajoutez \u00e0 votre main depuis votre Deck 1 monstre \"Marincesse\" qui a 1 Niveau de plus que le Niveau d'origine du monstre envoy\u00e9 au Cimeti\u00e8re.Lors de ce tour, vous ne pouvez pas Invoquer ou Invoquer Sp\u00e9cialement de monstres, sauf s'il s'agit de monstres \"Marincesse\".Cette Comp\u00e9tence ne peut \u00eatre utilis\u00e9e que si vous commencez le Duel avec un Deck/Extra Deck compos\u00e9 uniquement de monstres EAU de Type Cyberse. Cette Comp\u00e9tence ne peut \u00eatre utilis\u00e9e qu'une fois par Duel."
    },
    "ja": {
      "name": ""
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "supports": [
    "WATER",
    "Cyberse"
  ],
  "supportsArchetypes": [
    "Marincess"
  ],
  "releases": [
    {
      "character": "Blue Angel (Duel Links)",
      "type": "duel_reward"
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Marincess Transcend",
        "id": 715799
      }
    ]
  }
}
