=== DjobaDELATV/seygo_data/schema/v1/skill.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "title": "Skill",
  "description": "A Duel Links Skill (not a physical card).",
  "type": "object",
  "required": [
    "$schema",
    "id",
    "text",
    "cardType"
  ],
  "properties": {
    "$schema": {
      "const": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json"
    },
    "id": {
      "description": "The UUID of this skill.",
      "type": "string",
      "format": "uuid"
    },
    "text": {
      "description": "A map of languages to textual skill information.",
      "type": "object",
      "additionalProperties": {
        "description": "Textual information on the skill.",
        "type": "object",
        "required": [
          "name"
        ],
        "properties": {
          "name": {
            "description": "The name of the skill.",
            "type": "string"
          },
          "effect": {
            "description": "The effect text of the skill.",
            "type": "string"
          },
          "official": {
            "description": "Is this translation official?",
            "type": "boolean"
          }
        }
      }
    },
    "cardType": {
      "description": "Always 'skill-dl' for Duel Links skills.",
      "const": "skill-dl"
    },
    "skillType": {
      "description": "The type of skill (Legendary, Archive).",
      "type": "string"
    },
    "supports": {
      "description": "List of card names this skill supports or mentions.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "supportsArchetypes": {
      "description": "List of archetypes this skill supports.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "releases": {
      "description": "How this skill can be obtained.",
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "character",
          "type"
        ],
        "properties": {
          "character": {
            "description": "The character associated with this release.",
            "type": "string"
          },
          "type": {
            "description": "The release type (duel_reward, level_up, trader, etc.).",
            "type": "string"
          },
          "details": {
            "description": "Additional details (e.g., 'Level 20').",
            "type": "string"
          }
        }
      }
    },
    "externalIDs": {
      "description": "IDs from external sources.",
      "type": "object",
      "properties": {
        "yugipedia": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "type": "string"
              },
              "id": {
                "type": "integer"
              }
            }
          }
        }
      }
    }
  }
}

=== DjobaDELATV/seygo_data/skills/f3a3c81a-7f04-4032-8d29-d2f343702bb8.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "f3a3c81a-7f04-4032-8d29-d2f343702bb8",
  "text": {
    "en": {
      "name": "Winds of Deepest Winter",
      "effect": "You can only use this Skill's second effect one per Duel.\n1: At the beginning of the Duel, add 1 \"Windwitch - Winter Bell\" to your Extra Deck.\n2: Can be used before your normal draw if your LP are at 3000 or below. One of the cards from your normal draw this turn will be a random WIND Spellcaster monster from your Deck."
    },
    "fr": {
      "name": "Vents de l'Hiver Profond",
      "effect": "Vous ne pouvez utiliser le deuxi\u00e8me effet de cette Comp\u00e9tence qu'une fois par Duel.\n1 : Au d\u00e9but du Duel, ajoutez 1 \"Sorci\u00e8revent - Hiver Clochette\" \u00e0 votre Extra Deck.\n2 : Cette Comp\u00e9tence peut \u00eatre utilis\u00e9e avant votre pioche normale si vos LP sont de 3 000 ou moins. L'une des cartes de votre pioche normale de ce tour sera un monstre VENT Magicien al\u00e9atoire de votre Deck."
    },
    "ja": {
      "name": "\u771f\u51ac\u306e\u98a8",
      "effect": "\u3053\u306e\u30b9\u30ad\u30eb\u306e\u2461\u306e\u52b9\u679c\u306f\u30c7\u30e5\u30a8\u30eb\u4e2d\u306b\uff11\u5ea6\u3057\u304b\u4f7f\u7528\u3067\u304d\u306a\u3044\u3002\n\u2460\uff1a\u30c7\u30e5\u30a8\u30eb\u958b\u59cb\u6642\u306b\u767a\u52d5\u3059\u308b\u3002\uff25\uff38\u30c7\u30c3\u30ad\u306b\u300c\uff37\uff37\uff0d\u30a6\u30a3\u30f3\u30bf\u30fc\u30fb\u30d9\u30eb\u300d\u3092\uff11\u4f53\u8ffd\u52a0\u3059\u308b\u3002\n\u2461\uff1a\u81ea\u5206\u306e\uff2c\uff30\u304c\uff13\uff10\uff10\uff10\u4ee5\u4e0b\u306e\u5834\u5408\u3001\u81ea\u5206\u306e\u901a\u5e38\u306e\u30c9\u30ed\u30fc\u524d\u306b\u767a\u52d5\u3067\u304d\u308b\u3002\u3053\u306e\u30bf\u30fc\u30f3\u306e\u901a\u5e38\u306e\u30c9\u30ed\u30fc\uff11\u679a\u306f\u30c7\u30c3\u30ad\u304b\u3089\u30e9\u30f3\u30c0\u30e0\u306b\u9078\u3093\u3060\u9b54\u6cd5\u4f7f\u3044\u65cf\u30fb\u98a8\u5c5e\u6027\u30e2\u30f3\u30b9\u30bf\u30fc\u306b\u306a\u308b\u3002"
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "supports": [
    "Windwitch - Winter Bell (Duel Links)",
    "WIND",
    "Spellcaster"
  ],
  "releases": [
    {
      "character": "Rin (Duel Links)",
      "type": "level_up",
      "details": "Level 1"
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Winds of Deepest Winter",
        "id": 1101106
      }
    ]
  }
}

=== DjobaDELATV/seygo_data/skills/d6960c36-5365-4fc5-ad79-c3a86f0264e0.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "d6960c36-5365-4fc5-ad79-c3a86f0264e0",
  "text": {
    "en": {
      "name": "Field Exchange",
      "effect": "Can be used if your Life Points are at 3000 or below. Return up to 2 cards, including at least 1 Field Spell Card, from your hand to the bottom of your Deck. Then, draw the same number of cards as you returned.\nThis Skill can only be used once per Duel."
    },
    "fr": {
      "name": "\u00c9change de Terrain",
      "effect": "Cette Comp\u00e9tence ne peut \u00eatre utilis\u00e9e que si vos Life Points sont de 3 000 ou moins. Renvoyez jusqu'\u00e0 2 cartes, dont au moins 1 Carte Magie de Terrain de votre main au-dessous de votre Deck. Ensuite, piochez le m\u00eame nombre de cartes.\nCette Comp\u00e9tence ne peut \u00eatre utilis\u00e9e qu'une fois par Duel."
    },
    "ja": {
      "name": "\u30d5\u30a3\u30fc\u30eb\u30c9\u30fb\u30c1\u30a7\u30f3\u30b8",
      "effect": "\u81ea\u5206\u306e\u30e9\u30a4\u30d5\u30dd\u30a4\u30f3\u30c8\u304c\uff13\uff10\uff10\uff10\u4ee5\u4e0b\u306e\u5834\u5408\u306b\u4f7f\u7528\u3067\u304d\u308b\u3002\u81ea\u5206\u306f\u624b\u672d\u306e\u30d5\u30a3\u30fc\u30eb\u30c9\u9b54\u6cd5\u30ab\u30fc\u30c9\uff11\u679a\u3092\u30c7\u30c3\u30ad\u306e\u4e00\u756a\u4e0b\u306b\u623b\u3057\u305f\u5f8c\u3001\u30c7\u30c3\u30ad\u304b\u3089\uff11\u679a\u30c9\u30ed\u30fc\u3059\u308b\u3002\u3053\u306e\u30b9\u30ad\u30eb\u306f\u30c7\u30e5\u30a8\u30eb\u4e2d\u306b\uff11\u5ea6\u3057\u304b\u4f7f\u7528\u3067\u304d\u306a\u3044\u3002"
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "supports": [
    "Field Spell Card"
  ],
  "releases": [
    {
      "character": "Luna (Duel Links)",
      "type": "level_up",
      "details": "Level 20"
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Field Exchange",
        "id": 714938
      }
    ]
  }
}

=== DjobaDELATV/seygo_data/skills/a54d88b7-a44a-4558-b0f4-44400f3791de.json
{
  "$schema": "https://raw.githubusercontent.com/DjobaDELATV/seygo_data/main/schema/v1/skill.json",
  "id": "a54d88b7-a44a-4558-b0f4-44400f3791de",
  "text": {
    "en": {
      "name": "Cheer Up Fairies",
      "effect": "Can be used if your Life Points are at 3000 or below. Place 1 \"Fairy Cheer Girl\" from your Extra Deck on top of 1 \"Little Fairy\" you control. (This will be treated as an Xyz Summon.) This Skill can only be used once per Duel."
    },
    "fr": {
      "name": "Encouragement des F\u00e9es",
      "effect": "Cette Comp\u00e9tence peut \u00eatre utilis\u00e9e si vos Life Points sont de 3 000 ou moins. Posez 1 \"Pom-Pom F\u00e9e\" de votre Extra Deck au-dessus d'1 \"Petite F\u00e9e\" que vous contr\u00f4lez (ce sera consid\u00e9r\u00e9 comme une Invocation Xyz). Cette Comp\u00e9tence ne peut \u00eatre utilis\u00e9e qu'une fois par Duel."
    },
    "ja": {
      "name": "\u30d5\u30a7\u30a2\u30ea\u30fc\u30fb\u30c1\u30a2\u30fc\u30fb\u30a2\u30c3\u30d7",
      "effect": "\u81ea\u5206\u306e\u30e9\u30a4\u30d5\u30dd\u30a4\u30f3\u30c8\u304c\uff13\uff10\uff10\uff10\u4ee5\u4e0b\u306e\u3068\u304d\u306b\u4f7f\u7528\u3067\u304d\u308b\u3002\u81ea\u5206\u30d5\u30a3\u30fc\u30eb\u30c9\u4e0a\u306e\u300c\u30ea\u30c8\u30eb\u30fb\u30d5\u30a7\u30a2\u30ea\u30fc\u300d\uff11\u4f53\u306b\u3001\u30a8\u30af\u30b9\u30c8\u30e9\u30c7\u30c3\u30ad\u304b\u3089\u300c\u30d5\u30a7\u30a2\u30ea\u30fc\u30fb\u30c1\u30a2\u30fb\u30ac\u30fc\u30eb\u300d\uff11\u4f53\u3092\u30a8\u30af\u30b7\u30fc\u30ba\u53ec\u559a\u6271\u3044\u3068\u3057\u3066\u91cd\u306d\u308b\u3002\u3053\u306e\u30b9\u30ad\u30eb\u306f\u30c7\u30e5\u30a8\u30eb\u4e2d\u306b\uff11\u5ea6\u3057\u304b\u4f7f\u7528\u3067\u304d\u306a\u3044\u3002"
    }
  },
  "cardType": "skill-dl",
  "skillType": "Legendary",
  "supports": [
    "Little Fairy (Duel Links)",
    "Fairy Cheer Girl (Duel Links)"
  ],
  "releases": [
    {
      "character": "Tori Meadows (Duel Links)",
      "type": "duel_reward"
    }
  ],
  "externalIDs": {
    "yugipedia": [
      {
        "name": "Cheer Up Fairies",
        "id": 714262
      }
    ]
  }
}
